import React from 'react';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { 
  Sparkles, 
  Users, 
  Target, 
  BookOpen, 
  Calendar,
  CheckCircle,
  Star,
  ArrowRight,
  Zap,
  AlertTriangle,
  TrendingUp,
  Shield,
  Brain
} from 'lucide-react';
import { useMindmaker } from '../contexts/MindmakerContext';
import { supabase } from '../integrations/supabase/client';

export const ResultsScreen: React.FC = () => {
  const { state, resetMindmaker } = useMindmaker();
  const { discoveryData } = state;

  const getReadinessScore = () => {
    return discoveryData.aiInsights?.readinessScore || 65;
  };

  const getInvestmentRange = () => {
    return discoveryData.aiInsights?.investmentRange || '$25k-$45k';
  };

  const getRecommendedProgram = () => {
    const size = discoveryData.employeeCount;
    const urgency = discoveryData.implementationTimeline;
    
    if (size <= 50 && urgency?.includes('ASAP')) {
      return 'Executive Sprint + Intensive Bootcamp';
    } else if (size > 200) {
      return 'Enterprise AI Transformation Program';
    } else {
      return 'AI Literacy & Confidence Bootcamp';
    }
  };

  const handleScheduleConsultation = async () => {
    try {
      // Send comprehensive assessment notification to krish@fractionl.ai
      const { error } = await supabase.functions.invoke('send-assessment-notification', {
        body: {
          assessmentData: {
            // Contact Information
            businessName: discoveryData.businessName,
            contactName: discoveryData.contactName,
            contactEmail: discoveryData.contactEmail,
            contactRole: discoveryData.contactRole,
            
            // Business Details
            industry: discoveryData.industry,
            employeeCount: discoveryData.employeeCount,
            currentAIUse: discoveryData.currentAIUse,
            
            // Assessment Inputs
            biggestChallenges: discoveryData.biggestChallenges || [],
            leadershipVision: discoveryData.leadershipVision,
            successMetrics: discoveryData.successMetrics || [],
            learningPreferences: discoveryData.learningPreferences || [],
            implementationTimeline: discoveryData.implementationTimeline,
            
            // AI Generated Insights
            aiInsights: discoveryData.aiInsights
          }
        }
      });

      if (error) {
        // Silently log error without exposing to user
      }
    } catch (error) {
      // Silently handle error
    }
    
    // Always open Calendly regardless of email success/failure
    window.open('https://calendly.com/krish-raja/mindmaker-teams', '_blank');
  };


  const readinessScore = getReadinessScore();
  const investmentRange = getInvestmentRange();
  const recommendedProgram = getRecommendedProgram();

  return (
    <div className="min-h-screen bg-background">

      <div className="container-width py-6 sm:py-8 md:py-12 px-4 sm:px-6 md:px-0">
        <div className="max-w-4xl mx-auto space-y-6 sm:space-y-8">
          {/* Header */}
          <div className="text-center space-y-3 sm:space-y-4 px-4">
            <h1 className="text-4xl sm:text-5xl font-bold text-foreground leading-tight">
              AI Readiness Assessment Results
              <span className="block text-primary mt-2">{discoveryData.businessName}</span>
            </h1>
            <p className="body-md text-muted-foreground mobile-readable mx-auto">
              Your personalized AI transformation roadmap based on strategic assessment and industry expertise.
            </p>
            <Badge className="bg-green-500/10 text-green-600 border-green-500/20 text-xs sm:text-sm">
              <Brain className="w-3 h-3 mr-1" />
              AI-Powered Analysis Complete
            </Badge>
          </div>

          {/* AI Clone Disclaimer */}
          <div className="glass-card bg-amber-50/50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-800">
            <div className="p-6 text-center">
              <div className="flex items-center justify-center gap-2 mb-3">
                <Brain className="w-5 h-5 text-amber-600" />
                <span className="font-semibold text-amber-800 dark:text-amber-300">AI-Generated Insights</span>
              </div>
              <p className="text-sm text-amber-700 dark:text-amber-400 leading-relaxed">
                These results are generated by an AI clone of Krish and should be taken as preliminary insights only. 
                For accurate business recommendations tailored to your specific situation, 
                <strong className="font-semibold"> schedule a 1-on-1 strategy session with Krish below</strong>.
              </p>
            </div>
          </div>

          {/* Key Insights Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6 px-4 sm:px-0">
            <div className="glass-card card-mobile">
              <div className="card-header text-center">
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
                  <Brain className="w-6 h-6 sm:w-8 sm:h-8 text-primary" />
                </div>
                <h3 className="text-lg sm:text-xl font-semibold mb-2">AI Readiness Score</h3>
              </div>
              <div className="card-content text-center">
                <div className="text-2xl sm:text-3xl font-bold text-primary mb-2">{readinessScore}/100</div>
                <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
                  {readinessScore >= 80 ? 'Advanced - Ready for implementation' : 
                   readinessScore >= 60 ? 'Intermediate - Good foundation' : 
                   readinessScore >= 40 ? 'Beginner - High potential' :
                    'Early stage - Great opportunity'}
                </p>
              </div>
            </div>

            <div className="glass-card card-mobile">
              <div className="p-6 text-center">
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-accent/10 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
                  <BookOpen className="w-6 h-6 sm:w-8 sm:h-8 text-accent" />
                </div>
                <h3 className="text-lg sm:text-xl font-semibold mb-2">Learning Format</h3>
                <div className="text-base sm:text-lg font-semibold mb-2">
                  {discoveryData.learningPreferences?.includes('Live workshops') ? 'Live Workshops' :
                   discoveryData.learningPreferences?.includes('Self-paced') ? 'Self-Paced' :
                   discoveryData.learningPreferences?.includes('coaching') ? 'Coaching' :
                   'Mixed Approach'}
                </div>
                <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
                  Optimized for your team's preferences
                </p>
              </div>
            </div>

            <div className="glass-card card-mobile">
              <div className="p-6 text-center">
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-green-500/10 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
                  <Users className="w-6 h-6 sm:w-8 sm:h-8 text-green-600" />
                </div>
                <h3 className="text-lg sm:text-xl font-semibold mb-2">Team Size</h3>
                <div className="text-base sm:text-lg font-semibold mb-2">
                  {discoveryData.employeeCount} employees
                </div>
                <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
                  {discoveryData.employeeCount <= 50 ? 'Perfect for cohort training' :
                   discoveryData.employeeCount <= 200 ? 'Ideal for departmental rollout' :
                   'Requires enterprise approach'}
                </p>
              </div>
            </div>

            <div className="glass-card card-mobile">
              <div className="p-6 text-center">
                <div className="w-12 h-12 sm:w-16 sm:h-16 bg-blue-500/10 rounded-full flex items-center justify-center mx-auto mb-3 sm:mb-4">
                  <Target className="w-6 h-6 sm:w-8 sm:h-8 text-blue-600" />
                </div>
                <h3 className="text-lg sm:text-xl font-semibold mb-2">Investment Range</h3>
                <div className="text-base sm:text-lg font-semibold text-primary mb-2">
                  {investmentRange}
                </div>
                <p className="text-xs sm:text-sm text-muted-foreground leading-relaxed">
                  Based on scope and complexity
                </p>
              </div>
            </div>
          </div>

          {/* AI-Generated Analysis */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6">
            {/* Strategic Recommendations */}
            <div className="glass-card">
              <div className="p-6">
                <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
                  <TrendingUp className="w-5 h-5 text-primary" />
                  AI Strategy & Product Opportunities
                </h3>
                <div className="space-y-3">
                  {(discoveryData.aiInsights?.recommendations || [
                    'Implement AI literacy coaching for leadership confidence',
                    'Develop product strategy leveraging AI capabilities', 
                    'Create team enablement workshops focused on practical AI adoption'
                  ]).map((rec, index) => (
                    <div key={index} className="flex items-start gap-3 p-3 bg-muted/50 rounded-lg">
                      <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
                      <span className="text-sm">{rec}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Opportunity Areas */}
            <div className="glass-card">
              <div className="p-6">
                <h3 className="text-xl font-semibold mb-4 flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-purple-600" />
                  Growth & Learning Opportunities
                </h3>
                <div className="space-y-3">
                  {(discoveryData.aiInsights?.opportunityAreas || [
                    'Build AI-confident teams through strategic coaching',
                    'Leverage AI for competitive product advantages',
                    'Develop sustainable AI adoption frameworks'
                  ]).map((opp, index) => (
                    <div key={index} className="flex items-start gap-3 p-3 bg-purple-50 dark:bg-purple-950/20 rounded-lg">
                      <Star className="w-5 h-5 text-purple-600 mt-0.5 flex-shrink-0" />
                      <span className="text-sm">{opp}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Recommended Program */}
          <div className="glass-card bg-gradient-to-br from-primary/5 to-accent/5 border-primary/20">
            <div className="p-8">
              <div className="text-center space-y-6">
                <Badge className="bg-primary text-white px-4 py-2 text-lg">
                  Recommended Program for {discoveryData.businessName}
                </Badge>
                
                <h3 className="text-3xl font-bold">{recommendedProgram}</h3>
                
                <p className="body-md text-muted-foreground max-w-2xl mx-auto">
                  Tailored specifically for {discoveryData.industry} companies with {discoveryData.employeeCount} employees, 
                  focusing on {discoveryData.successMetrics?.slice(0, 2).join(' and ') || 'AI literacy and confidence'}.
                </p>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 sm:gap-8 mt-8">
                  <div className="space-y-4">
                    <h4 className="font-semibold text-left">Program Includes:</h4>
                    <div className="space-y-2 text-left">
                      <div className="flex items-center gap-2 text-sm">
                        <Star className="w-4 h-4 text-primary" />
                        Executive keynote & mindset transformation
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Star className="w-4 h-4 text-primary" />
                        Hands-on prompting & AI orchestration labs
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Star className="w-4 h-4 text-primary" />
                        AI literacy coaching & confidence building
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Star className="w-4 h-4 text-primary" />
                        Product strategy sessions leveraging AI
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Star className="w-4 h-4 text-primary" />
                        Team enablement workshops
                      </div>
                      <div className="flex items-center gap-2 text-sm">
                        <Star className="w-4 h-4 text-primary" />
                        Strategic AI thinking development
                      </div>
                    </div>
                  </div>
                  
                  <div className="space-y-4">
                    <h4 className="font-semibold text-left">Investment Range:</h4>
                    <div className="space-y-2 text-left">
                      <div className="text-3xl font-bold text-primary">{investmentRange}</div>
                      <div className="text-sm text-muted-foreground">
                        Final pricing based on scope, duration, and customization
                      </div>
                      <div className="text-sm text-primary font-medium">
                        🎯 ROI typically 300-500% within 12 months
                      </div>
                      <div className="text-xs text-muted-foreground">
                        Investment includes all materials, assessments, and follow-up support
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* CTA Button */}
          <div className="flex justify-center px-4 sm:px-0">
            <button 
              onClick={handleScheduleConsultation}
              className="btn-hero-primary text-base sm:text-lg px-6 sm:px-8 py-4 group touch-target-lg"
            >
              Schedule Strategy Call
              <Calendar className="w-4 h-4 sm:w-5 sm:h-5 ml-2 group-hover:translate-x-1 transition-transform" />
            </button>
          </div>

          {/* Trust & Social Proof */}
          <div className="glass-card bg-gradient-to-r from-muted/30 to-muted/10">
            <div className="p-6 text-center">
              <h4 className="font-semibold mb-4">Join leaders who've transformed their teams</h4>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-6 text-sm">
                <div>
                  <div className="text-2xl font-bold text-primary">500+</div>
                  <div className="text-muted-foreground">Executives trained</div>
                </div>
                <div>
                  <div className="text-2xl font-bold text-primary">95%</div>
                  <div className="text-muted-foreground">Confidence increase</div>
                </div>
                <div>
                  <div className="text-2xl font-bold text-primary">30 days</div>
                  <div className="text-muted-foreground">To see results</div>
                </div>
              </div>
            </div>
          </div>

          {/* Footer Action */}
          <div className="text-center pt-8">
            <button 
              onClick={resetMindmaker}
              className="btn-ghost text-muted-foreground hover:text-foreground"
            >
              Start Over with New Assessment
              <ArrowRight className="w-4 h-4 ml-2" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};